### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-clang#14]
I get this message when starting neovim:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/usr/local/etc/dotfiles/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 64, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/usr/local/etc/dotfiles/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 96, in gather_candidates
[deoplete]     self.load_sources()
[deoplete]   File "/usr/local/etc/dotfiles/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 278, in load_sources
[deoplete]     source = module.Source(self.__vim)
[deoplete]   File "/usr/local/etc/dotfiles/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 36, in __init__
[deoplete]     cl.Config.set_library_file(self.library_path)
[deoplete]   File "/usr/local/etc/dotfiles/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 3701, in set_library_file
[deoplete]     raise Exception("library file must be set before before using " \
[deoplete] Exception: library file must be set before before using any other functionalities in libclang.
[deoplete] An error has occurred. Please execute :messages command.
```

**Comment by zchee** [comment]
@nhooyr It's known bug :(

If you fast typing, will occur this error.
Caused by `libclang` is not caught up with your type speed.

I am looking for a solution.
