### ISSUE TITLE
Better install instructions?

### ISSUE THREAD

**Issue by Toqozz** [zchee/deoplete-clang#16]
I can't get this to work, I haven't installed deoplete sources before.

I tried adding deoplete-clang as a plugin with vim-plug, then editing my init.vim to match the README, however deoplete just throws errors now whenever I start typing.

I'm not sure what you mean by 'compile_commands.json' directory path.  How would I find where this directory is?

**Comment by Toqozz** [comment]
Here's the errors: 

```
[deoplete] Traceback (most recent call last):                                                                                                                
[deoplete]   File "/home/toqoz/.config/nvim/rplugin/python3/deoplete/__init__.py", line 49, in completion_begin                                              
[deoplete]     context)                                                                                                                                      
[deoplete]   File "/home/toqoz/.config/nvim/rplugin/python3/deoplete/deoplete.py", line 95, in gather_candidates                                             
[deoplete]     self.load_sources()                                                                                                                           
[deoplete]   File "/home/toqoz/.config/nvim/rplugin/python3/deoplete/deoplete.py", line 63, in load_sources                                                  
[deoplete]     'deoplete.sources.' + name, path).load_module()                                                                                               
[deoplete]   File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper                                                                 
[deoplete]   File "<frozen importlib._bootstrap_external>", line 806, in load_module                                                                         
[deoplete]   File "<frozen importlib._bootstrap_external>", line 665, in load_module                                                                         
[deoplete]   File "<frozen importlib._bootstrap>", line 268, in _load_module_shim                                                                            
[deoplete]   File "<frozen importlib._bootstrap>", line 693, in _load                                                                                        
[deoplete]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked                                                                               
[deoplete]   File "<frozen importlib._bootstrap_external>", line 662, in exec_module                                                                         
[deoplete]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed                                                                    
[deoplete]   File "/home/toqoz/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 5, in <module>                  
[deoplete]     from deoplete.util import load_external_module                                                                                                
[deoplete] ImportError: cannot import name 'load_external_module'                                                                                            
[deoplete] An error has occurred. Please execute :messages command. 
```

**Comment by zchee** [comment]
@Toqozz ok, I comment later.

**Comment by zchee** [comment]
@Toqozz Hi,
I will Modify the easy-to-understand REAMDE.
Can you set once again to look at it?

===

#### Simple answer
FYI, `g:deoplete#sources#clang#clang_complete_database` is **option**.
If you do not have `compile_commands.json`, not required it.
If have it, set `compile_commands.json` **exists dicectory path**.

e.g. llvm build directory
```bash
> tree -L 1 ~/src/llvm/build
├── CMakeCache.txt
├── CMakeFiles
├── CPackConfig.cmake
├── CPackSourceConfig.cmake
├── DummyConfigureOutput
├── LLVMBuild.cmake
├── bin
├── build.ninja
├── cmake
├── cmake_install.cmake
# exists
├── compile_commands.json
├── docs
├── examples
├── include
├── install_manifest.txt
├── install_manifest_libclang-headers.txt
├── install_manifest_libclang.txt
├── lib
├── libexec
├── libllvm-c.exports
├── projects
├── rules.ninja
├── share
├── test
├── tools
├── unittests
└── utils
```

set

```vim
let g:deoplete#sources#clang#clang_complete_database = $HOME/src/llvm/build
```

**Comment by Toqozz** [comment]
I see now, thank you.

**Comment by zchee** [comment]
@Toqozz :)
Commit: https://github.com/zchee/deoplete-clang/commit/d0c76cae9e86db85d2e79a374733be792db81113
