### ISSUE TITLE
TypeError: Can't convert 'NoneType' object to str implicitly

### ISSUE THREAD

**Issue by crondog** [zchee/deoplete-clang#4]
Using deoplete-clang causes an error in deoplete_clang.py:234 If I comment out the line `placeholder += chunk_spelling` it works correctly.

This happens when I try to complete at foo.
```
#include <vector>
using namespace std;
int main(int argc, char const* argv[])
{
    vector<int> foo;
    foo.
    return 0;
}
```

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/crondog/.cache/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 57, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/home/crondog/.cache/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 92, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/home/crondog/.cache/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 167, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/home/crondog/.cache/dein/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 105, in gather_candidates
[deoplete]     return list(map(self.parse_candidates, results))
[deoplete]   File "/home/crondog/.cache/dein/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 234, in parse_candidates
[deoplete]     placeholder += chunk_spelling
[deoplete] TypeError: Can't convert 'NoneType' object to str implicitly
[deoplete] An error has occurred. Please execute :messages command.
```

Minimal init.vim
```
set runtimepath+=~/.config/nvim/bundle/repos/github.com/Shougo/dein.vim
"endif
call dein#begin(expand('~/.cache/dein'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/deoplete.nvim')
call dein#add('zchee/deoplete-clang')
call dein#end()
let g:deoplete#enable_at_startup = 1

let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'
let g:deoplete#sources#clang#flags = ['-x', 'c++', '-std=c++11']
let g:deoplete#sources#clang#sort_algo = 'priority'
```

**Comment by Shougo** [comment]
I think it is fixed.  Please check it.

**Comment by crondog** [comment]
@Shougo It works great. Thanks :)

**Comment by zchee** [comment]
@Shougo Thanks :)
