### ISSUE TITLE
TranslationUnitLoadError

### ISSUE THREAD

**Issue by covercash2** [zchee/deoplete-clang#68]
## Environment Information

 - OS:
 - Neovim version:

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-clang/
let g:deoplete#enable_at_startup = 1
```

or, try use it [tests/deoplete-clang.vim](../tests/deoplete-clang.vim)

## The reproduce ways from neovim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

1. Set environment variables for neovim Python remote plugin

        export NVIM_PYTHON_LOG_FILE=/tmp/log
        export NVIM_PYTHON_LOG_LEVEL=DEBUG

2. Run nvim

        nvim -u minimal.vimrc

3. some works
3. cat /tmp/log_{PID}

## Upload the log file
 - `NVIM_PYTHON_LOG_FILE`
 - `$HOME`/.nvimlog

**Comment by stjepang** [comment]
I have the same problem.

**Comment by mikoim** [comment]
@covercash2 @stjepang You should read README.md carefully. `g:deoplete#sources#clang#libclang_path` and `g:deoplete#sources#clang#clang_header` are needed to work this plugin.

## example
```
let g:deoplete#sources#clang#libclang_path='/usr/lib/libclang.so'
let g:deoplete#sources#clang#clang_header='/usr/lib/clang'
```

**Comment by covercash2** [comment]
[here's the same init file](https://pastebin.com/d48cuBTR) i originally posted. also, this issue was only on macOS. 

i tried to be thorough in my original report.

**Comment by Shougo** [comment]
I think it depends clang version.

**Comment by wsdjeg** [comment]
I get same errors:

```

[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 136, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 151, in gather_candidates
[deoplete]     params)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 318, in get_completion
[deoplete]     tu = self.get_translation_unit(fname, args, buf)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 305, in get_translation_unit
[deoplete]     tu = self.index.parse(fname, args, buf, flags)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/clang/clang/cindex.py", line 2322, in parse
[deoplete]     self)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/clang/clang/cindex.py", line 2440, in from_source
[deoplete]     raise TranslationUnitLoadError("Error parsing translation unit.")
[deoplete] clang.cindex.TranslationUnitLoadError: Error parsing translation unit.
[deoplete] Could not get completions from: clang.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 136, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 151, in gather_candidates
[deoplete]     params)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 318, in get_completion
[deoplete]     tu = self.get_translation_unit(fname, args, buf)
[deoplete] Too many errors from "clang". This source is disabled until Neovim is restarted.
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 305, in get_translation_unit
[deoplete] Too many errors from "clang". This source is disabled until Neovim is restarted.
[deoplete]     tu = self.index.parse(fname, args, buf, flags)
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/clang/clang/cindex.py", line 2322, in parse
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 136, in gather_results
[deoplete]     self)
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/clang/clang/cindex.py", line 2440, in from_source
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 151, in gather_candidates
[deoplete]     raise TranslationUnitLoadError("Error parsing translation unit.")
[deoplete]     params)
[deoplete] clang.cindex.TranslationUnitLoadError: Error parsing translation unit.
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 318, in get_completion
[deoplete] Could not get completions from: clang.  Use :messages for error details.
[deoplete]     tu = self.get_translation_unit(fname, args, buf)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang.py", line 305, in get_translation_unit
[deoplete]     tu = self.index.parse(fname, args, buf, flags)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/clang/clang/cindex.py", line 2322, in parse
[deoplete]     self)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/clang/clang/cindex.py", line 2440, in from_source
[deoplete]     raise TranslationUnitLoadError("Error parsing translation unit.")
[deoplete] clang.cindex.TranslationUnitLoadError: Error parsing translation unit.
[deoplete] 
[deoplete] During handling of the above exception, another exception occurred:
[deoplete] 
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 59, in completion_begin
[deoplete]     self.gather_results(context), context['input'])
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 162, in gather_results
[deoplete]     self._sources.pop(source.name)
[deoplete] KeyError: 'clang'
[deoplete] Error while gathering completions.  Use :messages for error details.
```

**Comment by hwalinga** [comment]
Sometimes it was just a matter of removing the translation unit file again. (The .tu file) And it all works again.
