### ISSUE TITLE
clang TypeError

### ISSUE THREAD

**Issue by peder2tm** [zchee/deoplete-clang#85]
## Problems summary
Whenever I go to a c source file and write `#include ..` deoplete crashes with the following error.
The plugin used to work fine. Maybe it is because I have updated to clang 6.0.0 and the new version of the python api no longer accept unicode strings instead of byte strings.

I am on a fully updated Arch Linux with Neovim 0.2.2 and I have also checked out the newest versions of deoplete and deoplete-clang.

```
[deoplete] Traceback (most recent call last):
  File "/home/peter/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 226, in _gather_results
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/peter/.config/nvim/bundle/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 157, in gather_candidates
    params, refresh)
  File "/home/peter/.config/nvim/bundle/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 329, in get_completion
    tu = self.get_translation_unit(fname, args, buf)
  File "/home/peter/.config/nvim/bundle/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 313, in get_translation_unit
    tu.reparse(buf)
  File "/usr/lib/python3.6/site-packages/clang/cindex.py", line 2974, in reparse
    unsaved_files_array[i].name = name
TypeError: bytes or integer address expected instead of str instance
Error from clang: TypeError('bytes or integer address expected instead of str instance',).  Use :messages / see above for error details.
```

**Comment by peder2tm** [comment]
Anyways I have switched to deoplete-clang2 which works

**Comment by Shougo** [comment]
deoplete-clang does not support clang 6.0
